prod_cat_col = ['perfumery', 'health_beauty', 'sports_leisure', 'music',
       'electronics', 'toys', 'furniture_decor', 'watches_gifts',
       'pet_shop', 'bed_bath_table', 'market_place', 'housewares', 'art',
       'stationery', 'garden_tools', 'office_furniture', 'auto',
       'small_appliances', 'construction_tools_lights', 'cool_stuff',
       'cine_photo', 'food_drink', 'computers_accessories', 'food',
       'drinks', 'air_conditioning', 'baby', 'consoles_games',
       'fashion_bags_accessories', 'fashion_shoes',
       'construction_tools_safety', 'signaling_and_security',
       'la_cuisine', 'furniture_living_room', 'furniture_bedroom',
       'luggage_accessories', 'books_general_interest',
       'home_construction', 'kitchen_dining_laundry_garden_furniture',
       'construction_tools_construction',
       'industry_commerce_and_business', 'dvds_blu_ray', 'home_confort',
       'musical_instruments', 'home_comfort_2', 'pc_gamer', 'telephony',
       'tablets_printing_image', 'books_technical', 'flowers',
       'computers', 'home_appliances', 'arts_and_craftmanship',
       'home_appliances_2', 'costruction_tools_garden', 'party_supplies',
       'christmas_supplies', 'fixed_telephony',
       'fashion_childrens_clothes', 'fashion_sport', 'audio',
       'agro_industry_and_commerce', 'costruction_tools_tools',
       'fashion_underwear_beach', 'fashion_male_clothing',
       'fashio_female_clothing', 'books_imported',
       'small_appliances_home_oven_and_coffee', 'diapers_and_hygiene',
       'portable_cooking_and_food_prepareers', 'security_and_services',
       'furniture_mattress_and_upholstery', 'cds_dvds_musicals']
